apiVersion: apps
kind: Deployment
metadata:
  name: nginx-deem
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-demo
        image: nginx:1.14.2
        ports:
        - containerPort: 80
